version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: local-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: 123456
    ports:
      - "33060:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --log-bin=mysql-bin --binlog-format=ROW --server-id=1 --default-time-zone=Asia/Shanghai
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka1:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "19092:19092"
      - "19093:19093"
      - "19094:19094"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:19092,CONTROLLER://:19093,EXTERNAL://:19094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:19092,EXTERNAL://localhost:19094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    depends_on:
      - zookeeper
  kafka2:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "29092:29092"
      - "29093:29093"
      - "29094:29094"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:29092,CONTROLLER://:29093,EXTERNAL://:29094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:29092,EXTERNAL://localhost:29094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    depends_on:
      - kafka1
  kafka3:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "39092:39092"
      - "39093:39093"
      - "39094:39094"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:39092,CONTROLLER://:39093,EXTERNAL://:39094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:39092,EXTERNAL://localhost:39094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    depends_on:
      - kafka2

volumes:
  mysql_data:
